config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :lists, only: [:index, :show, :new, :create] do
    get "bookmarks/new", to: "bookmarks#new", as: "new_bookmark"
    post "bookmarks", to: "bookmarks#create", as: "bookmarks"
  end

  delete "bookmarks/:id", to: "bookmarks#destroy", as: "delete_bookmark"
  delete "lists/:id", to: "lists#destroy", as: "delete_list"
  
  resources :movies, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  
  validates :movie_id, presence: true, uniqueness: {scope: :list_id}
  validates :list_id, presence: true
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  has_one_attached :photo

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  # before_destroy :check_for_orders

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true

  private

  def check_for_orders
    if bookmarks.count > 0
      return false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy 
    @list = @bookmark.list
    redirect_to list_path(@list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

def index
  @lists = List.all
end

def show
  @list = List.find(params[:id])
  @bookmarks = Bookmark.where(list_id: @list.id)
  @movies = Movie.all
end

def new
  @list = List.new
end

def create
  @list = List.new(list_params)
  if @list.save
    redirect_to list_path(@list)
  else
    render :new
  end
end

def destroy
  @list = List.find(params[:id])
  @list.destroy
  redirect_to lists_path, status: :see_other
end

private

def list_params
  params.require(:list).permit(:name, :photo)
end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="main-container">
  <h1>Add a new bookmark</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie, collection: Movie.all %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-container">
    <div class="logo">
      <h1><%= link_to("Watchlist", lists_path) %></h1>
    </div>
    <div class="navbar-link-wrapper">
      <p><%= link_to("Add a new watchlist", new_list_path) %></p>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="main-container">
  <h1>Your lists</h1>

  <div class="list-cards">
    <% @lists.each do |list| %>
      <div class="list-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= list.photo.key == nil ? image_path("https://images.adsttc.com/media/images/58d5/3a58/e58e/ce48/a700/003f/large_jpg/002.jpg?1490369108%20(2)") : cl_image_path(list.photo.key, :cloud_name => "dnexemt1e") %>')">
        <p><%= link_to(list.name, list_path(list)) %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="main-container">
  <h1>Create a new list</h1>
  <%= simple_form_for [@list] do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="main-container">
  <div class="show-header">
    <h2><%= @list.name %></h2>
    <div class="show-navigation">
      <%= link_to("Add new bookmark", list_new_bookmark_path(@list), class: "btn btn-primary") %>
      <%= link_to("Delete this list", list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-warning") %>
    </div>
  </div>
  <div class="bookmarks-container">
    <% @bookmarks.each do |bookmark| %>
      <div class="bookmark-card">
        <img src="<%= bookmark.movie.poster_url%>" alt="" class="movie-poster">
        <h3 id="title-link"><%= link_to(bookmark.movie.title, movie_path(bookmark.movie)) %></h3>
        <div class="icons-wrapper">
          <p><i class="fa-solid fa-star"></i> <%= bookmark.movie.rating %> on IMDB</p>
          <%= link_to delete_bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fa-solid fa-trash-can"></i>
          <% end %>
        </div>
        <p id="comment-text">"<%= bookmark.comment %>"</p>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="main-container">
  <div class="movie-card">
    <div class="left-wrapper">
      <img src="<%= @movie.poster_url%>" alt="">
    </div>
    <div class="right-wrapper">
      <h2><%= @movie.title %></h2>
      <p><%= @movie.overview %></p>
      <p><i class="fa-solid fa-star"></i> <%= @movie.rating %></p>
    </div>
  </div>
</div>